USE LINEAGE_DB;
GO

IF OBJECT_ID('REGRESSION_TEST_SUGGESTIONS','U') IS NOT NULL DROP TABLE REGRESSION_TEST_SUGGESTIONS;
IF OBJECT_ID('SAVED_COMPARISONS','U') IS NOT NULL DROP TABLE SAVED_COMPARISONS;
IF OBJECT_ID('AUDIT_LOG','U') IS NOT NULL DROP TABLE AUDIT_LOG;
IF OBJECT_ID('FIELD_VERSIONS','U') IS NOT NULL DROP TABLE FIELD_VERSIONS;
IF OBJECT_ID('FIELD_DOWNSTREAM_MAPPINGS','U') IS NOT NULL DROP TABLE FIELD_DOWNSTREAM_MAPPINGS;
IF OBJECT_ID('FIELD_INTERPRETATIONS','U') IS NOT NULL DROP TABLE FIELD_INTERPRETATIONS;
IF OBJECT_ID('LOOKUP_VALUES','U') IS NOT NULL DROP TABLE LOOKUP_VALUES;
IF OBJECT_ID('REGULATORY_FIELDS','U') IS NOT NULL DROP TABLE REGULATORY_FIELDS;
IF OBJECT_ID('APP_JURISDICTION_ACCESS','U') IS NOT NULL DROP TABLE APP_JURISDICTION_ACCESS;
IF OBJECT_ID('APP_SCREEN_ACCESS','U') IS NOT NULL DROP TABLE APP_SCREEN_ACCESS;
IF OBJECT_ID('APP_USER_ROLES','U') IS NOT NULL DROP TABLE APP_USER_ROLES;
IF OBJECT_ID('APP_ROLES','U') IS NOT NULL DROP TABLE APP_ROLES;
IF OBJECT_ID('APP_USERS','U') IS NOT NULL DROP TABLE APP_USERS;
IF OBJECT_ID('JURISDICTIONS','U') IS NOT NULL DROP TABLE JURISDICTIONS;
GO

CREATE TABLE APP_USERS (
  USER_ID      BIGINT IDENTITY(1,1) PRIMARY KEY,
  USERNAME     NVARCHAR(100) NOT NULL,
  DISPLAY_NAME NVARCHAR(255) NOT NULL,
  EMAIL        NVARCHAR(255),
  STATUS       NVARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',
  CREATED_AT   DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  UPDATED_AT   DATETIME2     NULL,
  CONSTRAINT UQ_APP_USERS_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE APP_ROLES (
  ROLE_ID     BIGINT IDENTITY(1,1) PRIMARY KEY,
  ROLE_NAME   NVARCHAR(100) NOT NULL,
  DESCRIPTION NVARCHAR(MAX),
  CONSTRAINT UQ_APP_ROLES_NAME UNIQUE (ROLE_NAME)
);

CREATE TABLE APP_USER_ROLES (
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  CONSTRAINT PK_APP_USER_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_AUR_USER FOREIGN KEY (USER_ID) REFERENCES APP_USERS(USER_ID),
  CONSTRAINT FK_AUR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLES(ROLE_ID)
);

CREATE TABLE APP_SCREEN_ACCESS (
  SCREEN_ACCESS_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
  ROLE_ID          BIGINT        NOT NULL,
  SCREEN_CODE      NVARCHAR(100) NOT NULL,
  CAN_VIEW         BIT           NOT NULL DEFAULT 1,
  CONSTRAINT FK_ASA_ROLE        FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLES(ROLE_ID),
  CONSTRAINT UQ_ASA_ROLE_SCREEN UNIQUE (ROLE_ID, SCREEN_CODE)
);

CREATE TABLE APP_JURISDICTION_ACCESS (
  JURISDICTION_ACCESS_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
  ROLE_ID                BIGINT        NOT NULL,
  JURISDICTION_CODE      NVARCHAR(50)  NOT NULL,
  CAN_VIEW               BIT           NOT NULL DEFAULT 1,
  CONSTRAINT FK_AJA_ROLE       FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLES(ROLE_ID),
  CONSTRAINT UQ_AJA_ROLE_JCODE UNIQUE (ROLE_ID, JURISDICTION_CODE)
);

CREATE TABLE JURISDICTIONS (
  JURISDICTION_ID   BIGINT IDENTITY(1,1) PRIMARY KEY,
  JURISDICTION_CODE NVARCHAR(50)  NOT NULL,
  JURISDICTION_NAME NVARCHAR(255) NOT NULL,
  REGION            NVARCHAR(100),
  REGULATOR_NAME    NVARCHAR(255),
  REPORTING_REGIME  NVARCHAR(255),
  DESCRIPTION       NVARCHAR(MAX),
  OWNER_TEAM        NVARCHAR(255),
  STATUS            NVARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',
  CREATED_AT        DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  UPDATED_AT        DATETIME2     NULL,
  CONSTRAINT UQ_JURISDICTIONS_CODE UNIQUE (JURISDICTION_CODE)
);

CREATE TABLE REGULATORY_FIELDS (
  FIELD_ID              BIGINT IDENTITY(1,1) PRIMARY KEY,
  JURISDICTION_ID       BIGINT        NOT NULL,
  SYSTEM_NAME           NVARCHAR(255) NOT NULL,
  INTERNAL_FIELD_NAME   NVARCHAR(255) NOT NULL,
  BUSINESS_NAME         NVARCHAR(255) NOT NULL,
  EXTERNAL_DISPLAY_NAME NVARCHAR(255),
  DATA_TYPE             NVARCHAR(100),
  FIELD_CATEGORY        NVARCHAR(255),
  REPORTING_SECTION     NVARCHAR(255),
  IS_MANDATORY          BIT           NOT NULL DEFAULT 0,
  CRITICALITY           NVARCHAR(50)  NOT NULL DEFAULT 'MEDIUM',
  SOURCE_TYPE           NVARCHAR(100),
  OWNER_TEAM            NVARCHAR(255),
  STATUS                NVARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',
  DESCRIPTION           NVARCHAR(MAX),
  CREATED_AT            DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  UPDATED_AT            DATETIME2     NULL,
  CONSTRAINT FK_RF_JURISDICTION  FOREIGN KEY (JURISDICTION_ID) REFERENCES JURISDICTIONS(JURISDICTION_ID),
  CONSTRAINT UQ_RF_JCODE_FNAME   UNIQUE (JURISDICTION_ID, INTERNAL_FIELD_NAME)
);

CREATE TABLE FIELD_INTERPRETATIONS (
  INTERPRETATION_ID        BIGINT IDENTITY(1,1) PRIMARY KEY,
  FIELD_ID                 BIGINT    NOT NULL,
  BUSINESS_TRANSLATION     NVARCHAR(MAX),
  BUSINESS_INTERPRETATION  NVARCHAR(MAX),
  TECHNICAL_INTERPRETATION NVARCHAR(MAX),
  EXAMPLE_SCENARIO         NVARCHAR(MAX),
  ASSUMPTIONS              NVARCHAR(MAX),
  STATUS                   NVARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  CREATED_AT               DATETIME2    NOT NULL DEFAULT SYSUTCDATETIME(),
  UPDATED_AT               DATETIME2    NULL,
  CONSTRAINT FK_FI_FIELD FOREIGN KEY (FIELD_ID) REFERENCES REGULATORY_FIELDS(FIELD_ID)
);

CREATE TABLE FIELD_DOWNSTREAM_MAPPINGS (
  DOWNSTREAM_MAPPING_ID    BIGINT IDENTITY(1,1) PRIMARY KEY,
  FIELD_ID                 BIGINT         NOT NULL,
  DOWNSTREAM_NAME          NVARCHAR(255)  NOT NULL,
  DOWNSTREAM_TYPE          NVARCHAR(100),
  DOWNSTREAM_PATH_OR_FIELD NVARCHAR(1000),
  USAGE_TYPE               NVARCHAR(100),
  CRITICALITY              NVARCHAR(50),
  DESCRIPTION              NVARCHAR(MAX),
  CREATED_AT               DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),
  UPDATED_AT               DATETIME2      NULL,
  CONSTRAINT FK_FDM_FIELD FOREIGN KEY (FIELD_ID) REFERENCES REGULATORY_FIELDS(FIELD_ID)
);

CREATE TABLE FIELD_VERSIONS (
  VERSION_ID    BIGINT IDENTITY(1,1) PRIMARY KEY,
  FIELD_ID      BIGINT       NOT NULL,
  VERSION_NO    INT          NOT NULL,
  SNAPSHOT_JSON NVARCHAR(MAX),
  CHANGE_REASON NVARCHAR(MAX),
  CHANGED_BY    NVARCHAR(100),
  CHANGED_AT    DATETIME2    NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_FV_FIELD     FOREIGN KEY (FIELD_ID) REFERENCES REGULATORY_FIELDS(FIELD_ID),
  CONSTRAINT UQ_FV_FIELD_VNO UNIQUE (FIELD_ID, VERSION_NO)
);

CREATE TABLE AUDIT_LOG (
  AUDIT_ID     BIGINT IDENTITY(1,1) PRIMARY KEY,
  ENTITY_TYPE  NVARCHAR(100) NOT NULL,
  ENTITY_ID    BIGINT,
  ACTION_TYPE  NVARCHAR(100) NOT NULL,
  OLD_VALUE    NVARCHAR(MAX),
  NEW_VALUE    NVARCHAR(MAX),
  PERFORMED_BY NVARCHAR(100) NOT NULL,
  PERFORMED_AT DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  REMARKS      NVARCHAR(MAX)
);

CREATE TABLE LOOKUP_VALUES (
  LOOKUP_ID     BIGINT IDENTITY(1,1) PRIMARY KEY,
  LOOKUP_TYPE   NVARCHAR(100) NOT NULL,
  LOOKUP_CODE   NVARCHAR(100) NOT NULL,
  LOOKUP_LABEL  NVARCHAR(255) NOT NULL,
  DISPLAY_ORDER INT,
  IS_ACTIVE     BIT           NOT NULL DEFAULT 1,
  CONSTRAINT UQ_LV_TYPE_CODE UNIQUE (LOOKUP_TYPE, LOOKUP_CODE)
);

CREATE TABLE SAVED_COMPARISONS (
  COMPARISON_ID   BIGINT IDENTITY(1,1) PRIMARY KEY,
  COMPARISON_NAME NVARCHAR(255) NOT NULL,
  COMPARISON_TYPE NVARCHAR(100) NOT NULL,
  FIELD_IDS       NVARCHAR(MAX) NOT NULL,
  CREATED_BY      NVARCHAR(100) NOT NULL,
  CREATED_AT      DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE REGRESSION_TEST_SUGGESTIONS (
  SUGGESTION_ID    BIGINT IDENTITY(1,1) PRIMARY KEY,
  FIELD_ID         BIGINT        NOT NULL,
  TEST_NAME        NVARCHAR(255) NOT NULL,
  TEST_DESCRIPTION NVARCHAR(MAX),
  TEST_TYPE        NVARCHAR(100),
  PRIORITY         NVARCHAR(50),
  CREATED_AT       DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_RTS_FIELD FOREIGN KEY (FIELD_ID) REFERENCES REGULATORY_FIELDS(FIELD_ID)
);
GO
