USE LINEAGE_DB;
GO
CREATE INDEX IX_RF_JURISDICTION_ID ON REGULATORY_FIELDS(JURISDICTION_ID);
CREATE INDEX IX_RF_SYSTEM_NAME     ON REGULATORY_FIELDS(SYSTEM_NAME);
CREATE INDEX IX_RF_INTERNAL_NAME   ON REGULATORY_FIELDS(INTERNAL_FIELD_NAME);
CREATE INDEX IX_RF_BUSINESS_NAME   ON REGULATORY_FIELDS(BUSINESS_NAME);
CREATE INDEX IX_RF_CRITICALITY     ON REGULATORY_FIELDS(CRITICALITY);
CREATE INDEX IX_RF_STATUS          ON REGULATORY_FIELDS(STATUS);
CREATE INDEX IX_FDM_FIELD_ID       ON FIELD_DOWNSTREAM_MAPPINGS(FIELD_ID);
CREATE INDEX IX_AL_ENTITY          ON AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IX_ASA_ROLE_SCREEN    ON APP_SCREEN_ACCESS(ROLE_ID, SCREEN_CODE);
CREATE INDEX IX_AJA_ROLE_JCODE     ON APP_JURISDICTION_ACCESS(ROLE_ID, JURISDICTION_CODE);
GO
