USE LINEAGE_DB;
GO

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RF_JURISDICTION_ID' AND object_id=OBJECT_ID('REGULATORY_FIELDS'))
  DROP INDEX IX_RF_JURISDICTION_ID ON REGULATORY_FIELDS;
CREATE INDEX IX_RF_JURISDICTION_ID ON REGULATORY_FIELDS(JURISDICTION_ID);

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RF_SYSTEM_NAME' AND object_id=OBJECT_ID('REGULATORY_FIELDS'))
  DROP INDEX IX_RF_SYSTEM_NAME ON REGULATORY_FIELDS;
CREATE INDEX IX_RF_SYSTEM_NAME     ON REGULATORY_FIELDS(SYSTEM_NAME);

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RF_INTERNAL_NAME' AND object_id=OBJECT_ID('REGULATORY_FIELDS'))
  DROP INDEX IX_RF_INTERNAL_NAME ON REGULATORY_FIELDS;
CREATE INDEX IX_RF_INTERNAL_NAME   ON REGULATORY_FIELDS(INTERNAL_FIELD_NAME);

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RF_BUSINESS_NAME' AND object_id=OBJECT_ID('REGULATORY_FIELDS'))
  DROP INDEX IX_RF_BUSINESS_NAME ON REGULATORY_FIELDS;
CREATE INDEX IX_RF_BUSINESS_NAME   ON REGULATORY_FIELDS(BUSINESS_NAME);

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RF_CRITICALITY' AND object_id=OBJECT_ID('REGULATORY_FIELDS'))
  DROP INDEX IX_RF_CRITICALITY ON REGULATORY_FIELDS;
CREATE INDEX IX_RF_CRITICALITY     ON REGULATORY_FIELDS(CRITICALITY);

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RF_STATUS' AND object_id=OBJECT_ID('REGULATORY_FIELDS'))
  DROP INDEX IX_RF_STATUS ON REGULATORY_FIELDS;
CREATE INDEX IX_RF_STATUS          ON REGULATORY_FIELDS(STATUS);

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FDM_FIELD_ID' AND object_id=OBJECT_ID('FIELD_DOWNSTREAM_MAPPINGS'))
  DROP INDEX IX_FDM_FIELD_ID ON FIELD_DOWNSTREAM_MAPPINGS;
CREATE INDEX IX_FDM_FIELD_ID       ON FIELD_DOWNSTREAM_MAPPINGS(FIELD_ID);

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_AL_ENTITY' AND object_id=OBJECT_ID('AUDIT_LOG'))
  DROP INDEX IX_AL_ENTITY ON AUDIT_LOG;
CREATE INDEX IX_AL_ENTITY          ON AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_ASA_ROLE_SCREEN' AND object_id=OBJECT_ID('APP_SCREEN_ACCESS'))
  DROP INDEX IX_ASA_ROLE_SCREEN ON APP_SCREEN_ACCESS;
CREATE INDEX IX_ASA_ROLE_SCREEN    ON APP_SCREEN_ACCESS(ROLE_ID, SCREEN_CODE);

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_AJA_ROLE_JCODE' AND object_id=OBJECT_ID('APP_JURISDICTION_ACCESS'))
  DROP INDEX IX_AJA_ROLE_JCODE ON APP_JURISDICTION_ACCESS;
CREATE INDEX IX_AJA_ROLE_JCODE     ON APP_JURISDICTION_ACCESS(ROLE_ID, JURISDICTION_CODE);
GO
