// Domain model for the Advanced Enterprise Investigation UI.
// Deliberately generic — no project-specific or regulatory concepts are hardcoded
// (CLAUDE_INSTRUCTIONS.md §5). Every meaningful conclusion carries provenance (§3).

/** How a piece of knowledge came to exist. This is the platform's trust boundary. */
export type Provenance =
  | 'parsed'     // Parsed from code (deterministic)
  | 'derived'    // Derived from the knowledge graph
  | 'ai'         // Generated by AI (explanation, never invented fact)
  | 'inferred'   // Inferred from partial evidence
  | 'user'       // Added by a user
  | 'verified'   // Verified by a reviewer

/** A single evidence pointer back to source (CLAUDE_INSTRUCTIONS.md §3). */
export interface Evidence {
  id: string
  kind: 'java' | 'xslt' | 'xsd' | 'xml' | 'document' | 'graph'
  module?: string
  file: string
  symbol?: string          // class / method / template / element
  lineStart?: number
  lineEnd?: number
  xpath?: string
  sourceHash?: string
  snippet: string          // the actual code / markup excerpt
  language: 'java' | 'xml' | 'xsl' | 'xsd' | 'json' | 'text'
  caption: string
}

/** A short attributable statement: text + where it came from. */
export interface Attributed {
  text: string
  provenance: Provenance
  evidenceIds?: string[]
}

export type Criticality = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
export type ReviewStatus = 'UNREVIEWED' | 'IN_REVIEW' | 'REVIEWED' | 'FLAGGED'

/** A branch in the reconstructed decision logic. Order is significant (§17). */
export interface DecisionNode {
  id: string
  /** condition expression as reconstructed from source; null for the else/default leaf */
  condition: string | null
  label: string            // human phrasing of the branch
  provenance: Provenance
  evidenceIds: string[]
  /** value/outcome produced when this branch is taken (leaf) */
  outcome?: string
  children?: DecisionNode[]
}

/** One ordered stage in the source→output journey. */
export interface JourneyStage {
  id: string
  kind: 'source' | 'transform' | 'condition' | 'fallback' | 'intermediate' | 'xslt' | 'output'
  title: string
  detail: Attributed
  evidenceIds: string[]
}

export type FeedbackStatus =
  | 'SUBMITTED' | 'UNDER_REVIEW' | 'VERIFIED' | 'REJECTED' | 'PARTIALLY_ACCEPTED' | 'APPLIED'

export type FeedbackTarget =
  | 'description' | 'business' | 'technical' | 'layman' | 'source' | 'condition'
  | 'transformation' | 'fallback' | 'output' | 'chatbot' | 'missing' | 'parser'
  | 'ui' | 'general'

export interface Feedback {
  id: string
  fieldId: string
  target: FeedbackTarget
  author: string
  createdAt: string
  status: FeedbackStatus
  body: string
  /** reviewer note when verified/rejected/partial */
  resolution?: string
  /** true when this feedback conflicts with a code-derived fact (never hidden, §11) */
  conflictsWithCode?: boolean
}

export interface ReviewEvent {
  id: string
  fieldId: string
  actor: string
  at: string
  kind: 'note' | 'status' | 'checklist' | 'feedback' | 'generation' | 'parse'
  summary: string
  detail?: string
}

export interface ChecklistItem {
  id: string
  label: string
  done: boolean
}

export interface FieldSummary {
  id: string
  name: string             // business name
  internalName: string
  module: string
  group: string            // grouping dimension (e.g. system / domain) — generic
  dataType: string
  criticality: Criticality
  reviewStatus: ReviewStatus
  hasConditions: boolean
  hasFallback: boolean
  transformationCount: number
  /** ISO timestamp the trace was last generated — drives freshness indicator */
  tracedAt: string
  /** ISO timestamp source last changed — stale when newer than tracedAt */
  sourceChangedAt: string
  outputDestination: string
}

export interface Field extends FieldSummary {
  externalName: string
  description: Attributed
  business: Attributed          // business logic
  technical: Attributed         // technical logic
  layman: Attributed            // plain-language explanation
  conditions: Attributed[]
  transformations: Attributed[]
  fallbacks: Attributed[]
  output: Attributed
  decisionTree: DecisionNode
  journey: JourneyStage[]
  evidence: Evidence[]
  relatedFieldIds: string[]
  suggestedQuestions: string[]
  /** raw canonical field JSON (the machine-readable knowledge package) */
  canonical: Record<string, unknown>
  generatedWith?: { promptId: string; promptVersion: string; model: string; at: string }
}

export interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  text: string
  evidenceIds?: string[]
  suggestedFollowups?: string[]
}
