import type { ReactNode } from 'react'
import type { Provenance, Attributed, Evidence, Criticality } from './types'

const PROV_LABEL: Record<Provenance, string> = {
  parsed: 'Parsed from code',
  derived: 'Derived from graph',
  ai: 'Generated by AI',
  inferred: 'Inferred',
  user: 'Added by user',
  verified: 'Verified by reviewer',
}

/** Trust label — the platform's signature provenance chip. */
export function TrustLabel({ p, short }: { p: Provenance; short?: boolean }) {
  return (
    <span className={`tl tl--${p}`} title={PROV_LABEL[p]}>
      <span className={`tl__dot ${p}`} />
      {short ? p : PROV_LABEL[p]}
    </span>
  )
}

export function ProvenanceLegend() {
  return (
    <div className="legend">
      {(Object.keys(PROV_LABEL) as Provenance[]).map((p) => (
        <TrustLabel key={p} p={p} />
      ))}
    </div>
  )
}

export function CritTag({ c }: { c: Criticality }) {
  return (
    <span className="exec__crit" style={{ color: `var(--crit-${c.toLowerCase()})` }}>
      <span className={`crit-dot crit-${c}`} /> {c}
    </span>
  )
}

/** A citation chip that opens the evidence in the right rail. */
export function EvidenceCite({ ids, onOpen }: { ids?: string[]; onOpen?: (id: string) => void }) {
  if (!ids || ids.length === 0) return null
  return (
    <>
      {ids.map((id) => (
        <button key={id} className="ev-cite" onClick={() => onOpen?.(id)} title="View evidence">
          ⧉ {id.replace(/^ev-/, '')}
        </button>
      ))}
    </>
  )
}

/** Renders an attributed statement with its trust label and evidence citations. */
export function AttributedRow({
  a, label, onCite,
}: { a: Attributed; label?: string; onCite?: (id: string) => void }) {
  return (
    <div className="attr__row">
      <TrustLabel p={a.provenance} />
      <div className="body">
        {label && <div className="eyebrow" style={{ marginBottom: 4 }}>{label}</div>}
        <span className="prose" style={{ display: 'inline' }}>{a.text}</span>
        <EvidenceCite ids={a.evidenceIds} onOpen={onCite} />
      </div>
    </div>
  )
}

// ---- Lightweight, dependency-free syntax highlighting --------------------

const JAVA_KW = /\b(public|private|return|if|else|switch|case|new|final|void|class|static|import|package|for|while|null|true|false|this|throw|catch|try)\b/g

function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function highlight(code: string, lang: Evidence['language']): string {
  let h = esc(code)
  if (lang === 'java' || lang === 'json') {
    h = h.replace(/(\/\/[^\n]*)/g, '<span class="cm">$1</span>')
    h = h.replace(/(&quot;|")(?:[^"\\]|\\.)*\1/g, (m) => `<span class="str">${m}</span>`)
    h = h.replace(/'[^']*'/g, (m) => `<span class="str">${m}</span>`)
    h = h.replace(JAVA_KW, '<span class="kw">$1</span>')
    h = h.replace(/\b(\d+(?:\.\d+)?)\b/g, '<span class="num">$1</span>')
  } else if (lang === 'xsl' || lang === 'xml' || lang === 'xsd') {
    h = h.replace(/(&lt;\/?[\w:-]+)/g, '<span class="tag">$1</span>')
    h = h.replace(/([\w:-]+)=(&quot;[^&]*&quot;)/g, '<span class="attr2">$1</span>=<span class="str">$2</span>')
  }
  return h
}

export function CodeBlock({ ev }: { ev: Evidence }) {
  const lines = ev.snippet.split('\n')
  const start = ev.lineStart ?? 1
  return (
    <div>
      <div className="code-cap">
        <span>{ev.symbol ?? ev.file.split('/').pop()}</span>
        <span>{ev.language}{ev.sourceHash ? ` · ${ev.sourceHash}` : ''}</span>
      </div>
      <div className="code">
        <pre>
          {lines.map((ln, i) => (
            <div key={i}>
              <span className="ln">{start + i}</span>
              <span dangerouslySetInnerHTML={{ __html: highlight(ln, ev.language) || '&nbsp;' }} />
            </div>
          ))}
        </pre>
      </div>
    </div>
  )
}

export function Card({ title, right, children }: { title: string; right?: ReactNode; children: ReactNode }) {
  return (
    <div className="card">
      <div className="card__head">
        <h3>{title}</h3>
        {right}
      </div>
      <div className="card__body">{children}</div>
    </div>
  )
}

export function timeAgo(iso: string): string {
  const diff = Date.now() - Date.parse(iso)
  const h = Math.round(diff / 3_600_000)
  if (h < 1) return 'just now'
  if (h < 24) return `${h}h ago`
  const d = Math.round(h / 24)
  return `${d}d ago`
}
